# Generated by Django 3.2.4 on 2021-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.IntegerField(choices=[(1, 'Admins'), (2, 'Buyers'), (3, 'Vendors'), (4, 'Runners')], default=2),
        ),
    ]
